in_channels: 3
out_channels: 3
sfeb_channels: 48 # Width of the network (W)
num_blocks: 8 # Total number of adaptive MaxViT blocks (B)
blocks_per_stage: 2 # Number of adaptive MaxViT blocks in each stage (L)
num_stages: 4 # Number of stages (S)
num_heads: 4 # Number of attention heads (H)
ffn_dim: 192 # Feed-forward network dimension (typically 4x the width)
upscale_factor: 2 # Upscale factor for the final output
kernel_size: 3 # Convolutional kernel size
attention_kernel_size: 1 # Convolutional kernel size for adaptive MaxViT blocks and HFFB
batch_size: 32 # Mini-batch size
lr: 2e-4 # Learning rate
